# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print("Shape =",arr1.shape,"\nDimension =",arr1.ndim,"\nData Type =",arr1.dtype,"\nSize =",arr1.size,"\nType =",type(arr1))


Shape = (4,) 
Dimension = 1 
Data Type = int64 
Size = 4 
Type = <class 'numpy.ndarray'>


In [ ]:
# Attributes of 2-dimensional array
print("Shape =",arr2.shape,"\nDimension =",arr2.ndim,"\nData Type =",arr2.dtype,"\nSize =",arr2.size,"\nType =",type(arr2))

Shape = (2, 4) 
Dimension = 2 
Data Type = int64 
Size = 8 
Type = <class 'numpy.ndarray'>


In [ ]:
# Attributes of 3-dimensional array
print("Shape =",arr3.shape,"\nDimension =",arr3.ndim,"\nData Type =",arr3.dtype,"\nSize =",arr3.size,"\nType =",type(arr3))

Shape = (2, 2, 3) 
Dimension = 3 
Data Type = int64 
Size = 12 
Type = <class 'numpy.ndarray'>


In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(arr2)

In [ ]:
# Create an array of shape (10, 2) with only ones
arrone = np.ones((10,2))
arrone

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
arrzero = np.zeros((7,2,3))
arrzero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Create an array within a range of 0 and 100 with step 3
arrnum = np.arange(start = 0, stop = 100, step = 3)
arrnum

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arrrand1 = np.random.uniform(0,10,(7,2))
arrrand1

array([[1.2244581 , 7.46845439],
       [5.62620365, 9.94613696],
       [4.03629913, 1.59618037],
       [4.88684617, 7.12572349],
       [8.56893061, 8.18836994],
       [6.99353313, 3.49549629],
       [3.00056218, 9.85217578]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arrrand2 = np.random.rand(3,5)
arrrand2

array([[0.96514463, 0.25115896, 0.4002925 , 0.9293295 , 0.37117879],
       [0.18002727, 0.57730966, 0.42064035, 0.19225827, 0.66554406],
       [0.87077441, 0.99408196, 0.27689858, 0.83452723, 0.70482244]])

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arrrand3 = np.random.uniform(0,10,(4,6))
arrrand3

array([[3.74540119, 9.50714306, 7.31993942, 5.98658484, 1.5601864 ,
        1.5599452 ],
       [0.58083612, 8.66176146, 6.01115012, 7.08072578, 0.20584494,
        9.69909852],
       [8.32442641, 2.12339111, 1.81824967, 1.8340451 , 3.04242243,
        5.24756432],
       [4.31945019, 2.9122914 , 6.11852895, 1.39493861, 2.92144649,
        3.66361843]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arrrand4 = np.random.uniform(1,10,(3,7))
#arrrand4

# Find the unique numbers in the array you just created
uniq = np.unique(arrrand4)
uniq

array([1.30949669, 1.41805371, 1.58546434, 1.87904903, 2.09834411,
       2.53471711, 2.79706404, 3.32901983, 3.74152392, 4.96137244,
       5.10462986, 5.45659219, 5.62810995, 6.33173112, 6.46790367,
       7.15809724, 8.06658365, 8.27557613, 9.18388362, 9.53996984,
       9.6906883 ])

In [ ]:
# Find the 0'th index of the latest array you created
arrrand4[0]

array([5.10462986, 8.06658365, 2.79706404, 5.62810995, 6.33173112,
       1.41805371, 6.46790367])

In [ ]:
# Get the first 2 rows of latest array you created
arrrand4[0:2]

array([[5.10462986, 8.06658365, 2.79706404, 5.62810995, 6.33173112,
        1.41805371, 6.46790367],
       [2.53471711, 1.58546434, 9.53996984, 9.6906883 , 8.27557613,
        3.74152392, 1.87904903]])

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
arrrand4[0:2,0:2]

array([[5.10462986, 8.06658365],
       [2.53471711, 1.58546434]])

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arrrand5 = np.random.uniform(0,10,(3,5))
arrrand5

array([[6.62522284, 3.11711076, 5.20068021, 5.46710279, 1.84854456],
       [9.69584628, 7.75132823, 9.39498942, 8.9482735 , 5.97899979],
       [9.21874235, 0.88492502, 1.95982862, 0.45227289, 3.25330331]])

In [ ]:
# Add the two arrays together
arrrand2+arrrand5

array([[ 7.59036748,  3.36826972,  5.60097271,  6.39643229,  2.21972334],
       [ 9.87587355,  8.32863789,  9.81562977,  9.14053177,  6.64454385],
       [10.08951676,  1.87900698,  2.23672721,  1.28680012,  3.95812575]])

In [ ]:
# Create another array of ones of shape (5, 3)
arrone2 = np.ones((5,3))
arrone2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Try add the array of ones and the other most recent array together
arrone2+arrrand5.T # Can be fixed by taking transpose of the second matrix

array([[ 7.62522284, 10.69584628, 10.21874235],
       [ 4.11711076,  8.75132823,  1.88492502],
       [ 6.20068021, 10.39498942,  2.95982862],
       [ 6.46710279,  9.9482735 ,  1.45227289],
       [ 2.84854456,  6.97899979,  4.25330331]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
arrone3 = np.ones((3,5))
arrone3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Subtract the new array of ones from the other most recent array
arrone3 - arrrand5

array([[-5.62522284, -2.11711076, -4.20068021, -4.46710279, -0.84854456],
       [-8.69584628, -6.75132823, -8.39498942, -7.9482735 , -4.97899979],
       [-8.21874235,  0.11507498, -0.95982862,  0.54772711, -2.25330331]])

In [ ]:
# Multiply the ones array with the latest array
arrone3 * arrrand5

array([[6.62522284, 3.11711076, 5.20068021, 5.46710279, 1.84854456],
       [9.69584628, 7.75132823, 9.39498942, 8.9482735 , 5.97899979],
       [9.21874235, 0.88492502, 1.95982862, 0.45227289, 3.25330331]])

In [ ]:
# Take the latest array to the power of 2 using '**'
arrrand5**2

array([[43.89357773,  9.7163795 , 27.04707467, 29.88921295,  3.41711697],
       [94.00943504, 60.08308939, 88.26582612, 80.07159871, 35.74843847],
       [84.98521052,  0.78309229,  3.84092824,  0.20455077, 10.58398241]])

In [ ]:
# Do the same thing with np.square()
np.square(arrrand5)

array([[43.89357773,  9.7163795 , 27.04707467, 29.88921295,  3.41711697],
       [94.00943504, 60.08308939, 88.26582612, 80.07159871, 35.74843847],
       [84.98521052,  0.78309229,  3.84092824,  0.20455077, 10.58398241]])

In [ ]:
# Find the mean of the latest array using np.mean()
np.mean(arrrand5)

5.319811371724394

In [ ]:
# Find the maximum of the latest array using np.max()
np.max(arrrand5)

9.695846277645586

In [ ]:
# Find the minimum of the latest array using np.min()
np.min(arrrand5)

0.45227288910538066

In [ ]:
# Find the standard deviation of the latest array
np.std(arrrand5)

3.141481797893965

In [ ]:
# Find the variance of the latest array
np.var(arrrand5)

9.868907886499098

In [ ]:
# Reshape the latest array to (3, 5, 1)
arrrand5.reshape(3,5,1)

array([[[6.62522284],
        [3.11711076],
        [5.20068021],
        [5.46710279],
        [1.84854456]],

       [[9.69584628],
        [7.75132823],
        [9.39498942],
        [8.9482735 ],
        [5.97899979]],

       [[9.21874235],
        [0.88492502],
        [1.95982862],
        [0.45227289],
        [3.25330331]]])

In [ ]:
# Transpose the latest array
arrrand5.T

array([[6.62522284, 9.69584628, 9.21874235],
       [3.11711076, 7.75132823, 0.88492502],
       [5.20068021, 9.39498942, 1.95982862],
       [5.46710279, 8.9482735 , 0.45227289],
       [1.84854456, 5.97899979, 3.25330331]])

What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arrint1 = np.random.randint(0,10,9).reshape(3,3)
arrint2 = np.random.randint(0,10,6).reshape(3,2)
print(arrint1,"\n\n",arrint2)

[[1 4 7]
 [9 8 8]
 [0 8 6]] 

 [[8 7]
 [0 7]
 [7 2]]


In [ ]:
# Perform a dot product on the two newest arrays you created
np.dot(arrint1,arrint2)

array([[ 57,  49],
       [128, 135],
       [ 42,  68]])

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arrint1 = np.random.randint(0,10,12).reshape(4,3)
arrint2 = np.random.randint(0,10,12).reshape(4,3)
print(arrint1,"\n\n",arrint2)

[[0 7 2]
 [2 0 4]
 [9 6 9]
 [8 6 8]] 

 [[7 1 0]
 [6 6 7]
 [4 2 7]
 [5 2 0]]


In [ ]:
# Perform a dot product on the two newest arrays you created
# np.dot(arrint1,arrint2)

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(arrint1,arrint2.T)

array([[  7,  56,  28,  14],
       [ 14,  40,  36,  10],
       [ 69, 153, 111,  57],
       [ 62, 140, 100,  52]])

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arrint1 = np.random.randint(0,10,12).reshape(4,3)
arrint2 = np.random.randint(0,10,12).reshape(4,3)

In [ ]:
# Compare the two arrays with '>'
arrint1 > arrint2

array([[False,  True, False],
       [False, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='
arrint1 >= arrint2

array([[False,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Find which elements of the first array are greater than 7
arrint1 > 7

array([[False, False, False],
       [False, False,  True],
       [False, False,  True],
       [ True,  True, False]])

In [ ]:
# Which parts of each array are equal? (try using '==')
arrint1 == arrint2

array([[False, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False, False]])

In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(arrint1)

array([[2, 2, 4],
       [0, 4, 9],
       [6, 6, 8],
       [2, 9, 9]])

In [ ]:
# Sort the indexes of one of the arrays you just created
index = np.argsort(arrint1)
index

array([[0, 2, 1],
       [0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]])

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
max = np.argmax(arr1)
max

3

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
min = np.argmin(arr1)
min

0

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max = np.argmax(arrint1,axis=1)
max

array([1, 2, 2, 0])

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min = np.argmin(arrint1,axis=0)
min

array([1, 0, 0])

In [ ]:
# Create an array of normally distributed random numbers
arrnormal = np.random.normal(4,1,5)
arrnormal

array([2.53303211, 4.89262947, 3.89474287, 3.04465356, 3.58523537])

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.